Feat fetch enemies
Tomeiru/R-Type pull request #28
Opened 2023-03-01 22:11 UTC by titi0267

Fetch enemies, spawn enemies & fix clock for update

2023-03-02 12:49 UTC, AlexandreFRANTZ commented on common/ressources/Map.hpp
> +    class Map {
Add doxygen

2023-03-02 12:49 UTC, AlexandreFRANTZ commented on common/ressources/MapManager.hpp
> +    class MapManager {
Add doxygen

2023-03-02 12:49 UTC, AlexandreFRANTZ commented on common/ressources/RuntimeException.hpp
> +    class RuntimeException : public std::exception {
Add doxygen

2023-03-02 12:49 UTC, AlexandreFRANTZ commented on server/MapManager.hpp
> +    class MapManager {
Add doxygen

2023-03-02 12:50 UTC, AlexandreFRANTZ requested changes
Add all doxygen documentation

2023-03-02 14:26 UTC, ludovic-str requested changes
Clang-format

2023-03-04 09:30 UTC, AlexandreFRANTZ approved these changes

2023-03-04 15:03 UTC, ludovic-str approved these changes

2023-03-04 16:23 UTC, merged